### ISSUE TITLE
ValueError: Token is required for this provider, but not provided

### ISSUE THREAD

**Issue by wybert** [giswqs/streamlit-geospatial#38]
I have this error after run the app.py     
```
~/t/streamlit-geospatial ❯❯❯ streamlit run app.py                                                                                                                                         
2022-04-04 11:06:11.115 INFO    numexpr.utils: NumExpr defaulting to 8 threads.

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.0.0.45:8501

2022-04-04 11:06:13.323 Traceback (most recent call last):
  File "/Users/kang/mambaforge/lib/python3.9/site-packages/geemap/basemaps.py", line 231, in <module>
    name = item['name']
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kang/mambaforge/lib/python3.9/site-packages/streamlit/scriptrunner/script_runner.py", line 443, in _run_script
    exec(code, module.__dict__)
  File "/Users/kang/test/streamlit-geospatial/app.py", line 3, in <module>
    from apps import (
  File "/Users/kang/test/streamlit-geospatial/apps/gee.py", line 3, in <module>
    import geemap.foliumap as geemap
  File "/Users/kang/mambaforge/lib/python3.9/site-packages/geemap/__init__.py", line 7, in <module>
    from .geemap import *
  File "/Users/kang/mambaforge/lib/python3.9/site-packages/geemap/geemap.py", line 14, in <module>
    from .basemaps import ee_basemaps
  File "/Users/kang/mambaforge/lib/python3.9/site-packages/geemap/basemaps.py", line 239, in <module>
    ee_basemaps[name] = basemap_to_tiles(eval(basemap))
  File "/Users/kang/mambaforge/lib/python3.9/site-packages/ipyleaflet/leaflet.py", line 53, in basemap_to_tiles
    url = basemap.build_url(time=day, **kwargs)
  File "/Users/kang/mambaforge/lib/python3.9/site-packages/xyzservices/lib.py", line 451, in build_url
    raise ValueError(
ValueError: Token is required for this provider, but not provided. You can either update TileProvider or pass respective keywords to build_url().
```

**Comment by wybert** [comment]
> What is the geemap version?

# Name                    Version                   Build  Channel
geemap                    0.13.1                   pypi_0    pypi

**Comment by giswqs** [comment]
The latest geemap version v0.13.5 should resolve this issue.
